apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graylog-forwarder.fullname" . }}
  labels:
    {{- include "graylog-forwarder.labels" . | nindent 4 }}
data:
  GRAYLOG_FORWARDER_SERVER_HOSTNAME: {{ .Values.config.serverHostname | quote }}
  GRAYLOG_FORWARDER_API_ENABLED: {{ .Values.config.apiEnabled | quote }}
  {{- if .Values.config.apiEnabled }}
  GRAYLOG_FORWARDER_API_TCP_BIND_ADDRESS: {{ .Values.config.apiBindAddress | quote }}
  {{- end }}
  GRAYLOG_NODE_ID_FILE: {{ .Values.config.nodeIdFile | quote }}
  GRAYLOG_DATA_DIR: {{ .Values.config.dataDir | quote }}
  GRAYLOG_MESSAGE_JOURNAL_DIR: {{ .Values.config.journal.dir | quote }}
  GRAYLOG_MESSAGE_JOURNAL_MAX_AGE: {{ .Values.config.journal.maxAge | quote }}
  {{- with .Values.config.journal.maxSize }}
  GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: {{ . | quote }}
  {{- end }}
