{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graylog-forwarder.fullname" . }}
  labels:
    {{- include "graylog-forwarder.labels" . | nindent 4 }}
stringData:
  GRAYLOG_FORWARDER_GRPC_API_TOKEN: {{ .Values.config.apiToken | quote }}
{{- end }}
