{{ if .Values.datanode.enabled  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog-datanode
  labels:
    app: graylog-datanode
spec:
  replicas: {{ .Values.datanode.replicas  }}
  serviceName: graylog-datanode
  selector:
    matchLabels:
      app: graylog-datanode
  template:
    metadata:
      labels:
        app: graylog-datanode
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: graylog-datanode
          image: "{{ .Values.datanode.image.repository }}:{{ .Values.datanode.image.tag }}"
          imagePullPolicy: {{ .Values.datanode.image.imagePullPolicy }}
          env:
            - name: GRAYLOG_DATANODE_NODE_ID_FILE
              value: {{ .Values.datanode.env.graylogDatanodeIdFile }}
            - name: GRAYLOG_DATANODE_OPENSEARCH_HEAP
              value: {{ .Values.datanode.env.graylogDatanodeOpensearchHeap }}
            - name: GRAYLOG_JAVA_OPTS
              value: {{ .Values.datanode.env.graylogDatanodeJavaOpts }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRAYLOG_DATANODE_NODE_NAME
              value: $(POD_NAME).graylog-datanode.{{ .Release.Namespace }}.svc.cluster.local
            - name: GRAYLOG_DATANODE_OPENSEARCH_DISCOVERY_SEED_HOSTS
              # @todo: loop through replica count to generate this
              value: "graylog-datanode-0.graylog-datanode.{{ .Release.Namespace }}.svc.cluster.local,graylog-datanode-1.graylog-datanode.{{ .Release.Namespace }}.svc.cluster.local,graylog-datanode-2.graylog-datanode.{{ .Release.Namespace }}.svc.cluster.local"
            - name: GRAYLOG_DATANODE_PASSWORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.graylogSecretName }}
                  key: graylog-password-secret
            - name: GRAYLOG_DATANODE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.graylogSecretName }}
                  key: mongo-db-uri
          ports:
            - name: api
              containerPort: {{ .Values.datanode.service.ports.api }}
              protocol: TCP
            - name: data
              containerPort: {{ .Values.datanode.service.ports.data }}
              protocol: TCP
            - name: config
              containerPort: {{ .Values.datanode.service.ports.config }}
              protocol: TCP
          volumeMounts:
            - name: "data"
              mountPath: {{ .Values.datanode.persistence.data.mountPath }}
            - name: native-libs
              mountPath: /native_libs
            # @todo: volume mount this
            - name: plugins
              mountPath: /plugin
          {{- if .Values.datanode.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.datanode.service.ports.api }}
            initialDelaySeconds: {{ .Values.datanode.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.datanode.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.datanode.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.datanode.livenessProbe.failureThreshold }} 
            successThreshold: {{ .Values.datanode.livenessProbe.successThreshold }} 
          {{- end }}
          {{- if .Values.datanode.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.datanode.service.ports.api }}
            initialDelaySeconds: {{ .Values.datanode.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.datanode.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.datanode.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.datanode.readinessProbe.failureThreshold }} 
            successThreshold: {{ .Values.datanode.readinessProbe.successThreshold }} 
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.datanode.service.ports.api }}
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- with .Values.datanode.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: native-libs
          emptyDir: {}
        - name: plugins
          emptyDir: {}
      {{- if not .Values.datanode.persistence.data.enabled}}
        - name: data
          emptyDir: {}
      {{- end }}

  volumeClaimTemplates:
  {{- if .Values.datanode.persistence.data.enabled }}
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.datanode.persistence.data.storageClass }}
      storageClassName: {{ .Values.datanode.persistence.data.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.datanode.persistence.data.size }}
  {{- end }}
{{- end }}
