{{- if not .Values.global.existingSecret }}
{{/*
Lookup secrets to restore
*/}}
{{- $secretName := include "graylog.secretsName" . }}
{{- $this := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $backupName := include "graylog.backupSecretName" . }}
{{- $backup := lookup "v1" "Secret" .Release.Namespace $backupName  }}
{{- $mongoSecretName := include "graylog.mongodb.secretName" . }}
{{- $mongoSecret := lookup "v1" "Secret" .Release.Namespace $mongoSecretName }}

{{/*
  Graylog sha256 and pepper
*/}}
{{- $graylogSha := include "graylog.rootPassword" . | sha256sum | b64enc }}
{{- $graylogPepper := include "graylog.secretPepper" . | b64enc }}

{{/*
MongoDB secrets
*/}}
{{- $mongoRootPassword := randAlphaNum 16 | b64enc }}
{{- $mongoReplicaSetKey := randAlphaNum 32 | b64enc }}
{{- $mongoDbPassword := randAlphaNum 16 | b64enc }}
{{- $mongoMetricsPassword := randAlphaNum 16 | b64enc }}

{{/*
  Restore backup
*/}}
{{- if $this }}
  {{- $graylogPepper = index $this.data "GRAYLOG_PASSWORD_SECRET" }}
{{ else if $backup }}
  {{- $graylogPepper = index $backup.data "graylog-secret" }}
{{- end }}
{{- if $backup }}
  {{- $mongoRootPassword = index $backup.data "mongodb-root-password" | default $mongoRootPassword }}
  {{- $mongoReplicaSetKey = index $backup.data "mongodb-replica-set-key" | default $mongoReplicaSetKey  }}
  {{- $mongoDbPassword = index $backup.data "mongodb-passwords" | default $mongoDbPassword  }}
  {{- $mongoMetricsPassword = index $backup.data "mongodb-metrics-password" | default $mongoMetricsPassword  }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $backupName }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" . | nindent 4 }}
    helm.sh/resource-policy: keep
data:
  mongodb-root-password: {{ $mongoRootPassword }}
  mongodb-replica-set-key: {{ $mongoReplicaSetKey }}
  mongodb-passwords: {{ $mongoDbPassword }}
  mongodb-metrics-password: {{ $mongoMetricsPassword }}
  graylog-secret: {{ $graylogPepper }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $mongoSecretName }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" . | nindent 4 }}
data:
  mongodb-root-password: {{ $mongoRootPassword }}
  {{- if eq .Values.mongodb.architecture "replicaset" }}
  mongodb-replica-set-key: {{ $mongoReplicaSetKey }}
  {{- end }}
  {{- if .Values.mongodb.auth.username }}
  mongodb-passwords: {{ $mongoDbPassword }}
  {{- end }}
  {{- if .Values.mongodb.metrics.username }}
  mongodb-metrics-password: {{ $mongoMetricsPassword }}
  {{- end }}
---
{{/*
  Mongo DB URI: "mongodb://user:password@{mongo-pod}.{mongo-service}:27017/graylog"
*/}}
{{- $mongoServiceName := printf "%s-mongodb" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- $mongoPort := int .Values.mongodb.service.ports.mongodb }}
{{- $mongoUser := .Values.mongodb.auth.username | default "graylog" }}
{{- $mongoDb := .Values.mongodb.auth.database | default "graylog" }}
{{- $mongoAuth := "" }}
{{- if $mongoSecret }}
  {{- $mongoAuth = index $mongoSecret.data "mongodb-passwords" }}
  {{- if empty $mongoAuth }}
    {{- $mongoAuth = index $mongoSecret.data "mongodb-root-password" }}
    {{- $mongoUser = .Values.mongodb.auth.rootUser }}
  {{- end }}
  {{ $mongoAuth = $mongoAuth | b64dec | printf "%s:%s@" $mongoUser }}
{{- end }}
{{- $builder := list }}
{{- range $i := .Values.mongodb.replicaCount | int | until }}
{{- $builder = printf "%s-%d.%s-headless:%d" $mongoServiceName $i $mongoServiceName $mongoPort | append $builder }}
{{- end }}
{{- $mongoUri := printf "mongodb://%s%s/%s" $mongoAuth (join "," $builder) $mongoDb | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" . | nindent 4 }}
data:
  GRAYLOG_MONGODB_URI: {{ $mongoUri }}
  GRAYLOG_ROOT_USERNAME: {{ .Values.graylog.config.rootUsername | default "admin" | b64enc }}
  GRAYLOG_PASSWORD_SECRET: {{ $graylogPepper }}
  GRAYLOG_ROOT_PASSWORD_SHA2: {{ $graylogSha }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graylog.fullname" . | printf "%s-mongo-creds" }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
        - name: update-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for required secrets..."

              start_time=$(date +%s)
              timeout=120  # seconds

              while true; do
                now=$(date +%s)
                elapsed=$((now - start_time))

                # Get both secrets
                mongo_secret=$(kubectl get secret {{ $mongoSecretName }} -n {{ .Release.Namespace }} -o json 2>/dev/null)
                target_secret=$(kubectl get secret {{ $secretName }} -n {{ .Release.Namespace }} -o json 2>/dev/null)

                # Check that both exist
                if [ -n "$mongo_secret" ] && [ -n "$target_secret" ]; then
                  # Extract values
                  pass=$(echo "$mongo_secret" | jq -r '.data["mongodb-passwords"]')
                  uri=$(echo "$target_secret" | jq -r '.data["GRAYLOG_MONGODB_URI"]')

                  # Check if both values are non-empty
                  if [ "$pass" != "null" ] && [ "$uri" != "null" ] && [ -n "$pass" ] && [ -n "$uri" ]; then
                    echo "Secrets are ready. Proceeding to update..."
                    break
                  fi
                fi

                if [ "$elapsed" -ge "$timeout" ]; then
                  echo "Timed out waiting for secrets. Exiting with error."
                  exit 1
                fi

                sleep 5
              done

              # Decode password
              pass=$(echo "$pass" | base64 -d)
              uri=$(echo "$uri" | base64 -d)

              # Check if URI already contains '@'
              if echo "$uri" | grep -q "@"; then
                echo "MongoDB URI already contains credentials. Nothing to do."
                exit 0
              fi

              echo "Updating credentials for MongoDB URI..."
              uri=$(echo -n $uri | sed "s|mongodb://|mongodb://{{ $mongoUser }}:$pass@|" | base64 -w 0)

              # Patch the secret
              kubectl patch secret {{ $secretName }} -n {{ .Release.Namespace }} \
                --type merge \
                -p "{\"data\":{\"GRAYLOG_MONGODB_URI\":\"$uri\"}}"
          env:
            - name: KUBECONFIG
              value: /home/.kube/config
          volumeMounts:
            - name: kubeconfig
              mountPath: /home/.kube
              readOnly: true
      restartPolicy: OnFailure
      serviceAccountName: {{ include "graylog.serviceAccountName" . }}
      volumes:
        - name: kubeconfig
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 600
{{- end }}