{{- if not .Values.global.existingSecret }}
{{- $secretName := include "graylog.secretsName" . -}}
{{/*
  Mongo DB URI: "mongodb://user:password@{mongo-pod}.{mongo-service}:27017/graylog"
*/}}
{{- $mongoSname := printf "%s-mongodb" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- $mongoPort := int .Values.mongodb.service.ports.mongodb }}
{{- $mongoUser := "graylog" }}
{{- if .Values.mongodb.auth.usernames }}{{ $mongoUser = index .Values.mongodb.auth.usernames 0 }}{{ end }}
{{- $mongoDb := "graylog" }}
{{- if .Values.mongodb.auth.databases }}{{ $mongoDb = index .Values.mongodb.auth.databases 0 }}{{ end }}
{{- $mongoAuth := "" }}
{{- $mongoSecret := lookup "v1" "Secret" .Release.Namespace $mongoSname }}
{{- if $mongoSecret }}
  {{- $mongoAuth = index $mongoSecret.data "mongodb-passwords" }}
  {{- if empty $mongoAuth }}
    {{- $mongoAuth = index $mongoSecret.data "mongodb-root-password" }}
    {{- $mongoUser = .Values.mongodb.auth.rootUser }}
  {{- end }}
  {{ $mongoAuth = $mongoAuth | b64dec | printf "%s:%s@" $mongoUser }}
{{- end }}
{{- $mongoBuilder := list }}
{{- range $i := .Values.mongodb.replicaCount | int | until }}
{{- $mongoBuilder = printf "%s-%d.%s-headless:%d" $mongoSname $i $mongoSname $mongoPort | append $mongoBuilder }}
{{- end }}
{{- $mongoUri := printf "mongodb://%s%s/%s" $mongoAuth (join "," $mongoBuilder) $mongoDb | b64enc -}}
{{/*
  Graylog sha256 and pepper
*/}}
{{- $passwdSha := include "graylog.rootPassword" . | sha256sum | b64enc }}
{{- $passwdSecret := include "graylog.secretPepper" . | b64enc }}
{{- $this := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if $this }}
  {{- $passwdSecret = index $this.data "graylog-password-secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" . | nindent 4 }}
data:
  mongo-db-uri: {{ $mongoUri }}
  graylog-root-username: {{ .Values.graylog.config.rootUsername | default "admin" | b64enc }}
  graylog-password-secret: {{ $passwdSecret }}
  graylog-password-sha2: {{ $passwdSha }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graylog.fullname" . | printf "%s-mongo-creds" }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
        - name: update-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for required secrets..."

              start_time=$(date +%s)
              timeout=120  # seconds

              while true; do
                now=$(date +%s)
                elapsed=$((now - start_time))

                # Get both secrets
                mongo_secret=$(kubectl get secret {{ $mongoSname }} -n {{ .Release.Namespace }} -o json 2>/dev/null)
                target_secret=$(kubectl get secret {{ $secretName }} -n {{ .Release.Namespace }} -o json 2>/dev/null)

                # Check that both exist
                if [ -n "$mongo_secret" ] && [ -n "$target_secret" ]; then
                  # Extract values
                  pass=$(echo "$mongo_secret" | jq -r '.data["mongodb-passwords"]')
                  uri=$(echo "$target_secret" | jq -r '.data["mongo-db-uri"]')

                  # Check if both values are non-empty
                  if [ "$pass" != "null" ] && [ "$uri" != "null" ] && [ -n "$pass" ] && [ -n "$uri" ]; then
                    echo "Secrets are ready. Proceeding to update..."
                    break
                  fi
                fi

                if [ "$elapsed" -ge "$timeout" ]; then
                  echo "Timed out waiting for secrets. Exiting with error."
                  exit 1
                fi

                sleep 5
              done

              # Decode password
              pass=$(echo "$pass" | base64 -d)
              uri=$(echo "$uri" | base64 -d)

              # Check if URI already contains '@'
              if echo "$uri" | grep -q "@"; then
                echo "MongoDB URI already contains credentials. Nothing to do."
                exit 0
              fi

              echo "Updating credentials for MongoDB URI..."
              uri=$(echo $uri | sed "s|mongodb://|mongodb://{{ $mongoUser }}:$pass@|" | base64 -w 0)

              # Patch the secret
              kubectl patch secret {{ $secretName }} -n {{ .Release.Namespace }} \
                --type merge \
                -p "{\"data\":{\"mongo-db-uri\":\"$uri\"}}"

          env:
            - name: KUBECONFIG
              value: /home/.kube/config
          volumeMounts:
            - name: kubeconfig
              mountPath: /home/.kube
              readOnly: true
      restartPolicy: OnFailure
      serviceAccountName: {{ include "graylog.serviceAccountName" . }}
      volumes:
        - name: kubeconfig
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 600
{{- end }}