{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graylog.serviceAccountName" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-patch-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    resourceNames: [ {{ include "graylog.fullname" .  | printf "%s-0"}} ]
    verbs: [ "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "graylog.serviceAccountName" . | printf "%s-rb" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "graylog.serviceAccountName" . }}
roleRef:
  kind: Role
  name: secret-patch-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
