{{- if and .Values.datanode.enabled .Values.datanode.podDisruptionBudget.enabled }}
{{- range include "graylog.datanode.groups" $ | fromYamlArray }}
{{- if ge (.replicas | int) 1 }}
{{- $fixed := dict "app.kubernetes.io/component" "datanode" "app" "graylog-datanode" }}
{{- with .groupLabel }}
{{- $_ := set $fixed "graylog-datanode-group" . }}
{{- end }}
{{- $pdb := .podDisruptionBudget }}
{{- $subject := printf "datanode node group %q" (default "<primary>" .name) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .pdbName }}
  namespace: {{ $.Release.Namespace }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" $pdb.labels "fixed" $fixed "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" $pdb.annotations "indent" 2) }}
spec:
  {{ include "graylog.pdb.limit" (dict "pdb" $pdb "subject" $subject) }}
  selector:
    matchLabels:
      app: graylog-datanode
      {{- with .groupLabel }}
      graylog-datanode-group: {{ . }}
      {{- end }}
      {{- include "graylog.selectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
