{{- if .Values.datanode.podDisruptionBudget.enabled }}
{{- range include "graylog.datanode.groups" $ | fromYamlArray }}
{{- if ge (.replicas | int) 1 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .pdbName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: graylog-datanode
    {{- with .groupLabel }}
    graylog-datanode-group: {{ . }}
    {{- end }}
    {{- include "graylog.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ .podDisruptionBudget.minAvailable | default 3 | int }}
  selector:
    matchLabels:
      app: graylog-datanode
      {{- with .groupLabel }}
      graylog-datanode-group: {{ . }}
      {{- end }}
      {{- include "graylog.selectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
