{{- $c := .Values.datanode.config }}
{{- $sk := $c.s3ClientDefaultSecretKey }}
{{- $ak := $c.s3ClientDefaultAccessKey }}
{{- $endpoint := $c.s3ClientDefaultEndpoint }}
{{- if or (not $ak | and $sk) (not $endpoint | and $ak) (not $sk | and $endpoint) }}
  {{ fail "All three values are required: datanode.config.s3ClientDefaultEndpoint, datanode.config.s3ClientDefaultSecretKey, and datanode.config.s3ClientDefaultAccessKey" }}
{{- end }}
{{- range include "graylog.datanode.groups" $ | fromYamlArray }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmapName }}
data:
  JAVA_OPTS: {{ .config.javaOpts | quote }}
  GRAYLOG_DATANODE_NODE_ID_FILE: {{ .config.nodeIdFile | default "/var/lib/graylog-datanode/node-id" | quote }}
  GRAYLOG_DATANODE_OPENSEARCH_HEAP: {{ .config.opensearchHeap | quote }}
  GRAYLOG_DATANODE_SKIP_PREFLIGHT_CHECKS: {{ .config.skipPreflightChecks | quote }}
  GRAYLOG_DATANODE_NODE_SEARCH_CACHE_SIZE: {{ .config.nodeSearchCacheSize | quote }}
  {{- with .roles }}
  GRAYLOG_DATANODE_NODE_ROLES: {{ join "," . | quote }}
  {{- end }}
  GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_ENDPOINT: {{ .config.s3ClientDefaultEndpoint | quote }}
  GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_REGION: {{ .config.s3ClientDefaultRegion | quote }}
  GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_PROTOCOL: {{ .config.s3ClientDefaultProtocol | quote }}
  GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_PATH_STYLE_ACCESS: {{ .config.s3ClientDefaultPathStyleAccess | quote }}
{{- end }}
