# Example Graylog Secret
# If you wish to generate your own graylog-secret the following keys are required. All values should
# be base64 encoded before applying to your cluster. Then supply the secret name as 
# global.existingSecretName: ""
#
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: graylog-secret-example
data:
  # Mongo DB URI with valid credentials and location of the Mongo cluster
  GRAYLOG_MONGODB_URI: mongodb://admin:password@somewhere.local:27017/graylog_2?authSource=admin
  # Graylog admin user name
  GRAYLOG_ROOT_USERNAME: "some-user"
  # Graylog admin user's password
  GRAYLOG_PASSWORD_SECRET: "my-password"
  # Graylog admin user's password SHA2 value. To get this value, see step 4 of 
  # https://go2docs.graylog.org/current/downloading_and_installing_graylog/docker_installation.htm
  GRAYLOG_ROOT_PASSWORD_SHA2: 6fa2288c361becce3e30ba4c41be7d8ba01e3580566f7acc76a7f99994474c46
