apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graylog.datanode.secretsName" . }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.datanode.labels "fixed" (dict "app" "graylog-datanode") "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.datanode.annotations "indent" 2) }}
data:
  {{- with .Values.datanode.config.s3ClientDefaultSecretKey }}
  GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_SECRET_KEY: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.datanode.config.s3ClientDefaultAccessKey }}
  GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_ACCESS_KEY: {{ . | b64enc }}
  {{- end }}