{{- if .Values.datanode.enabled }}
{{- range include "graylog.datanode.groups" $ | fromYamlArray }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .fullname }}
  labels:
    app: graylog-datanode
    {{- with .groupLabel }}
    graylog-datanode-group: {{ . }}
    {{- end }}
    {{- include "graylog.labels" $ | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" $ | nindent 4 }}
spec:
  replicas: {{ .replicas | int }}
  serviceName: {{ include "graylog.datanode.service.name" $ }}
  selector:
    matchLabels:
      app: graylog-datanode
      {{- with .groupLabel }}
      graylog-datanode-group: {{ . }}
      {{- end }}
      {{- include "graylog.selectorLabels" $ | nindent 6 }}
  updateStrategy:
    type: {{ .updateStrategy.type | default "RollingUpdate" | quote }}
    {{- if .updateStrategy.type | default "RollingUpdate" | eq "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .updateStrategy.rollingUpdate.maxUnavailable | default 1 }}
      {{- with .updateStrategy.rollingUpdate.partition }}
      partition: {{ int . }}
      {{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        app: graylog-datanode
        {{- with .groupLabel }}
        graylog-datanode-group: {{ . }}
        {{- end }}
        {{- include "graylog.selectorLabels" $ | nindent 8 }}
      annotations:
        checksum/config: {{ include "graylog.datanode.configChecksum" $ }}
        checksum/secret: {{ include "graylog.secretsChecksum" $ }}
      {{- with .podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      dnsPolicy: ClusterFirst
      {{- with $.Values.datanode.image.imagePullSecrets | default $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "graylog.serviceAccountName" $ }}
      {{- end }}
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: graylog-datanode
          image: {{ include "graylog.datanode.image" $ }}
          imagePullPolicy: {{ $.Values.datanode.image.imagePullPolicy }}
          {{- with .containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .configmapName }}
            - secretRef:
                name: {{ include "graylog.datanode.secretsName" $ }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRAYLOG_DATANODE_NODE_NAME
              value: $(POD_NAME).{{ include "graylog.datanode.service.name" $ }}.{{ $.Release.Namespace }}.svc.cluster.local
            - name: GRAYLOG_DATANODE_OPENSEARCH_DISCOVERY_SEED_HOSTS
              value: {{ include "graylog.datanode.hosts" $ }}
            - name: GRAYLOG_DATANODE_PASSWORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "graylog.secretsName" $ }}
                  key: GRAYLOG_PASSWORD_SECRET
            - name: GRAYLOG_DATANODE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "graylog.secretsName" $ }}
                  key: GRAYLOG_MONGODB_URI
            {{- include "graylog.env" . | indent 12 }}
          ports:
            - name: api
              containerPort: {{ .service.ports.api | default 8999 | int }}
              protocol: TCP
            - name: data
              containerPort: {{ .service.ports.data | default 9200 | int }}
              protocol: TCP
            - name: config
              containerPort: {{ .service.ports.config | default 9300 | int }}
              protocol: TCP
          volumeMounts:
            - name: "data"
              mountPath: {{ .persistence.data.mountPath | default "/var/lib/graylog-datanode" | quote }}
            - name: native-libs
              mountPath: {{ .persistence.nativeLibs.mountPath | default "/native_libs" | quote }}
          {{- if .livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .service.ports.api | default 8999 | int }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .livenessProbe.periodSeconds | int }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds | int }}
            failureThreshold: {{ .livenessProbe.failureThreshold | int }}
            successThreshold: {{ .livenessProbe.successThreshold | int }}
          {{- end }}
          {{- if .readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .service.ports.api | default 8999 | int }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .readinessProbe.periodSeconds | int }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds | int }}
            failureThreshold: {{ .readinessProbe.failureThreshold | int }}
            successThreshold: {{ .readinessProbe.successThreshold | int }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      tolerations:
      {{- with .tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with .affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .persistence.data.enabled .persistence.nativeLibs.enabled | not }}
      volumes:
        {{- if not .persistence.nativeLibs.enabled }}
        - name: native-libs
          emptyDir: {}
        {{- end }}
        {{- if not .persistence.data.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
      {{- end }}
  {{- if or .persistence.data.enabled .persistence.nativeLibs.enabled }}
  volumeClaimTemplates:
    {{- if .persistence.data.enabled }}
    - metadata:
        name: data
      spec:
        accessModes:
        {{- if .persistence.data.accessModes }}
        {{- range .persistence.data.accessModes }}
          - {{ . | quote }}
        {{- end }}
        {{- else }}
          - "ReadWriteOnce"
        {{- end }}
        {{- with .dataStorageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .persistence.data.size | default "8Gi" | quote }}
    {{- end }}
    {{- if .persistence.nativeLibs.enabled }}
    - metadata:
        name: native-libs
      spec:
        accessModes:
        {{- if .persistence.nativeLibs.accessModes }}
        {{- range .persistence.nativeLibs.accessModes }}
          - {{ . | quote }}
        {{- end }}
        {{- else }}
          - "ReadWriteOnce"
        {{- end }}
        {{- with .nativeLibsStorageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .persistence.nativeLibs.size | default "8Gi" | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
