{{- if .Values.mongodb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graylog.mongodb.serviceAccountName" . }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.mongodb.serviceAccount.labels "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.mongodb.serviceAccount.annotations "indent" 2) }}
automountServiceAccountToken: {{ if eq (.Values.mongodb.serviceAccount.automount | toString) "false" }}false{{ else }}true{{ end }}
{{- if empty .Values.mongodb.serviceAccount.role.rules | not | and .Values.mongodb.serviceAccount.role.create }}
{{- $roleName := include "graylog.mongodb.serviceAccountName" . | printf "%s-role" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.mongodb.serviceAccount.role.labels "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.mongodb.serviceAccount.role.annotations "indent" 2) }}
rules: {{ .Values.mongodb.serviceAccount.role.rules | toYaml | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "graylog.mongodb.serviceAccountName" . | printf "%s-rb" }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.mongodb.serviceAccount.role.labels "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.mongodb.serviceAccount.role.annotations "indent" 2) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "graylog.mongodb.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}