{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graylog.serviceAccountName" . }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.serviceAccount.labels "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.serviceAccount.annotations "indent" 2) }}
automountServiceAccountToken: {{ dig "automount" true .Values.serviceAccount }}
{{- if empty .Values.serviceAccount.role.rules | not | and .Values.serviceAccount.role.create }}
{{- $roleName := include "graylog.serviceAccountName" . | printf "%s-role" | trunc 63 | trimSuffix "-" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.serviceAccount.role.labels "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.serviceAccount.role.annotations "indent" 2) }}
rules: {{ .Values.serviceAccount.role.rules | toYaml | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "graylog.serviceAccountName" . | printf "%s-rb" | trunc 63 | trimSuffix "-" }}
  {{- include "graylog.metadata.labels" (dict "context" $ "labels" .Values.serviceAccount.role.labels "indent" 2) }}
  {{- include "graylog.metadata.annotations" (dict "context" $ "annotations" .Values.serviceAccount.role.annotations "indent" 2) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "graylog.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
