{{- if and .Values.graylog.enabled .Values.ingress.web.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.web.name" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
  {{- $clusterissuer := include "cert-manager.clusterissuer.existing.name" . }}
  {{- if or $clusterissuer .Values.ingress.config.tls.issuer.existingName .Values.ingress.config.tls.issuer.autoissue.enabled }}
    {{- if $clusterissuer }}
    cert-manager.io/cluster-issuer: {{ $clusterissuer }}
    {{- else }}
    cert-manager.io/issuer: {{ include "cert-manager.issuer.name" . | coalesce .Values.ingress.config.tls.issuer.existingName }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.ingress.web.className "nginx" | and .Values.ingress.config.defaultBackend.enabled }}
    nginx.ingress.kubernetes.io/default-backend: {{ include "fallback.name" . }}
  {{- end }}
  {{- with .Values.ingress.web.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.config.defaultBackend.enabled }}
  defaultBackend:
    service:
      name: {{ include "fallback.name" . }}
      port:
        number: 3000
  {{- end }}
  {{- with .Values.ingress.web.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.web.tls }}
  tls:
    {{- range .Values.ingress.web.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.web.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if not .paths }}
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "graylog.serviceName" $ }}
                port:
                  number: {{ $.Values.graylog.custom.service.ports.app }}
          {{- end }}
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "graylog.serviceName" $ }}
                port:
                  number: {{ $.Values.graylog.custom.service.ports.app }}
          {{- end }}
    {{- end }}
{{- end }}
