{{- if and .Values.graylog.enabled .Values.ingress.web.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.web.name" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
  {{- if or .Values.ingress.config.tls.issuer.autoissue.enabled .Values.ingress.config.tls.issuer.existingName }}
    cert-manager.io/issuer: {{ include "cert-manager.issuer.name" . | coalesce .Values.ingress.config.tls.issuer.existingName }}
  {{- end }}
  {{- with .Values.ingress.web.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.web.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.web.tls }}
  tls:
    {{- range .Values.ingress.web.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.web.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "graylog.serviceName" $ }}
                port:
                  number: {{ $.Values.graylog.custom.service.ports.app }}
          {{- end }}
    {{- end }}
{{- end }}
