{{- if and .Values.graylog.config.geolocation.enabled .Values.graylog.config.geolocation.maxmindGeoIp.enabled }}
{{- $geoSecretName := include "graylog.fullname" . | printf "%s-geoip-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $geoSecretName }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" . | nindent 4 }}
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.graylog.config.geolocation.maxmindGeoIp.accountId | int | quote | trimAll "\"" | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.graylog.config.geolocation.maxmindGeoIp.licenseKey | quote | trimAll "\"" | b64enc }}
{{- $cronJobName := include "graylog.fullname" . | printf "%s-geoip-update" }}
{{- $claimName := printf "%s-%s" (include "graylog.volumeName" .) (include "graylog.fullname" .) }}
{{- $cronSchedule := .Values.graylog.config.geolocation.maxmindGeoIp.cronSchedule | default "0 0 * * *" }}
{{- $hookIsEnabled := .Values.graylog.config.geolocation.maxmindGeoIp.postInstallRun | default true }}
{{- range $i := include "graylog.replicas" . | default 2 | int | until }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%d" $cronJobName $i }}
spec:
  schedule: {{ $cronSchedule }}
  jobTemplate:
    spec:
      {{- list $geoSecretName $claimName $i | include "graylog.geoip.job.spec" | nindent 6 }}
{{- if $hookIsEnabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%d-hook" $cronJobName $i }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
{{- list $geoSecretName $claimName $i | include "graylog.geoip.job.spec" | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}